CREATE TABLE sensores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(30) NOT NULL,
);


CREATE TABLE alertas (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_alerta     VARCHAR2(10) NOT NULL,
    descricao       VARCHAR2(255),
    origem          VARCHAR2(30), --api, ultre ou umidade
    data_hora       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_tipo_alerta 
    CHECK (tipo_alerta IN ('OK', 'RUIM'))
);