-- Cria tabelas
CREATE TABLE sensores (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(30) NOT NULL
);

CREATE TABLE alertas (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sensor   NUMBER NOT NULL,
    tipo_alerta VARCHAR2(10) NOT NULL,
    descricao   VARCHAR2(255),
    data_hora   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alerta_sensor FOREIGN KEY (id_sensor) REFERENCES sensores(id),
    CONSTRAINT chk_tipo_alerta  CHECK (tipo_alerta IN ('OK', 'RUIM'))
);

-- Insere os dois sensores
INSERT INTO sensores (tipo) VALUES ('umidade');
INSERT INTO sensores (tipo) VALUES ('ultrassom');
COMMIT;